Hooks:Add("LocalizationManagerPostInit", "shin_assaultcornertext", function(loc)
	LocalizationManager:add_localized_strings({
		["hud_assault_FG_cover1"] = "KILL EACHOTHER, BUT IT'S GOOD INVERSES",
		["hud_assault_FG_cover2"] = "RARE FOOTAGE OF DRAGAN ACTUALLY ANGRY",
		["hud_assault_FG_cover3"] = "THUGGERY AT THE FULLEST OF DISPLAYS",
		["hud_assault_FG_cover4"] = "ANOTHER FIGHT IS COMING YOUR WAY",
		["hud_assault_FG_cover5"] = "THE WHEEL OF FATE IS TURNING",
		["hud_assault_FG_cover6"] = "THIS IS TUNA WITH BACON",
		["hud_assault_FG_cover7"] = "THIS BATTLE IS ABOUT TO EXPLODE",
		["hud_assault_FG_cover8"] = "TIME TO DEAL REAL CROATIAN DAMAGE",
		["hud_assault_FG_cover9"] = "SMOKIN SICK STYLE",
		["hud_assault_FG_cover10"] = "YOU HAVE STARTLED THE HORDE",
		["hud_assault_FG_cover11"] = "YOU CANNOT ESCAPE FROM CROSSING FATE",
		["hud_assault_FG_cover12"] = "LIVE AND LET DIE",
		["hud_assault_FG_cover13"] = "WHERE YO CURLY MUSTACHE AT",
		["hud_assault_FG_cover14"] = "WELCOME TO HYPER HEISTING",
		["hud_assault_faction_swat"] = "VS. SWAT TEAM",
		["hud_assault_faction_fbi"] = "VS. FBI SQUADRON",
		["hud_assault_faction_fbitsu"] = "VS. FBI & GENSEC",
		["hud_assault_faction_ftsu"] = "VS. GENSEC TASKFORCE",
		["hud_assault_faction_zeal"] = "VS. ZEAL LEGION",
		["hud_assault_faction_psc"] = "VS. MURKY BATTALION",
		["hud_assault_faction_mad"] = "VS. REAPERS",
		["hud_assault_cover"] = "STAY IN COVER",
		["hud_assault_assault"] = "ASSAULT IN PROGRESS",
		["menu_toggle_one_down"] = "SHIN SHOOTOUT",
		["menu_one_down"] = "SHIN SHOOTOUT",
		["menu_risk_pd"] = "Simple, but challenging. Stone cold.",
		["menu_risk_swat"] = "SWAT team wants to arrest you. We are cool.",
		["menu_risk_fbi"] = "You're up against the feds. A nice breeze.",
		["menu_risk_special"] = "The FBI wants you gone. A warm, summer day.",
		["menu_risk_easy_wish"] = "GENSEC is out to get you! Getting hot in here!",
		["menu_risk_elite"] = "New units rolling in! More heat around the corner!",
		["menu_risk_sm_wish"] = "VERSUS! ZEAL LEGION! FIGHT!!!",
		["menu_cs_modifier_heavies"] = "All enemies except Bulldozers and FBIs now have body armor.",
		["menu_cs_modifier_heavy_sniper"] = "Adds a chance for Sniperdozers to spawn.",
		["menu_cs_modifier_dozer_lmg"] = "EVERYTHING IS HORRIBLE!",
		["menu_cs_modifier_dozer_rage"] = "Adds a chance for Swat Bronco Ninja Marksmen to spawn.",
		["menu_cs_modifier_dozer_immune"] = "Enemies are much more aggressive.",
		["menu_cs_modifier_shield_phalanx"] = "Shotgunners have a chance to be replaced by a Gensec Saiga SWAT.",
		["menu_cs_modifier_no_hurt"] = "SHIN SHOOTOUT is now enabled.",
		["menu_cs_modifier_cloaker_tear_gas"] = "Cloakers are now silent while charging and move 25% faster.",
		["menu_cs_modifier_enemy_health_damage"] = "Enemies deal an additional 15% more damage, are 10% more accurate, have 15% more health, turn 5% faster and detect you slightly faster in Stealth.",
	})
end)
